plugins {
    id 'com.github.jruk8.plugin-conventions' version 'v1.3.6'
}

repositories {
    maven {
        name = 'okaeriReleases'
        url = 'https://repo.okaeri.cloud/releases'
    }
    maven {
        name = 'placeholderapi'
        url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
    }
}

dependencies {
    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    // Okaeri Config System
    // Core (Required)
    implementation 'eu.okaeri:okaeri-configs-yaml-bukkit:5.0.13'
    // Bukkit objects support (Location, ItemStack, etc.)
    implementation 'eu.okaeri:okaeri-configs-serdes-bukkit:5.0.13'
    // Adventure / MiniMessage & common Java types support
    implementation 'eu.okaeri:okaeri-configs-serdes-commons:5.0.13'

    // Cloud v2 Command System
    implementation platform('org.incendo:cloud-bom:2.0.0')
    implementation platform('org.incendo:cloud-minecraft-bom:2.0.0')

    implementation 'org.incendo:cloud-annotations'
    implementation 'org.incendo:cloud-paper'
    implementation 'org.incendo:cloud-minecraft-extras'

    // PlaceholderAPI
    compileOnly 'me.clip:placeholderapi:2.11.6'
}

tasks.named('shadowJar') {
    def targetPackage = "${pluginGroup}.libs"
    relocate 'eu.okaeri', "${targetPackage}.okaeri"
    relocate 'org.incendo.cloud', "${targetPackage}.cloud"
}
