plugins {
    id 'com.github.jruk8.plugin-conventions' version 'v1.2.8'
}

repositories {
    maven {
        name = 'okaeriReleases'
        url = 'https://repo.okaeri.cloud/releases'
    }
    maven {
        name = 'placeholderapi'
        url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
    }
    maven {
        name = 'codemc'
        url = 'https://repo.codemc.org/repository/maven-public/'
    }
}

dependencies {
    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    // Okaeri Config System
    // Core (Required)
    implementation 'eu.okaeri:okaeri-configs-yaml-bukkit:5.0.13'
    // Bukkit objects support (Location, ItemStack, etc.)
    implementation 'eu.okaeri:okaeri-configs-serdes-bukkit:5.0.13'
    // Adventure / MiniMessage & common Java types support
    implementation 'eu.okaeri:okaeri-configs-serdes-commons:5.0.13'

    // Cloud v2 Command System
    implementation 'org.incendo:cloud-paper:2.0.0'
    implementation 'org.incendo:cloud-annotations:2.1.0'

    // PlaceholderAPI
    compileOnly 'me.clip:placeholderapi:2.11.6'

    // Testing
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'
    testImplementation 'com.github.seeseemelk:MockBukkit-v1.21:3.133.2'
}
