name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    uses: jruk8/plugin-conventions/.github/workflows/docs.yml@v1.2.8
